# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheBibileReader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TheBibileReader
  pod 'ZipArchive', '~> 1.4.0'
  
  
  
  platform :ios, '8.0'
  pod 'DTCoreText'
  pod 'MWPhotoBrowser', '~> 2.1.2'
end
